name: 🐍 • CI

on:
  workflow_call:
    secrets:
      token:
        description: "The token to use for Codecov"
        required: true
    inputs:
      setup-z3:
        description: "Whether to set up Z3"
        default: false
        type: boolean
      z3-version:
        description: "The version of Z3 to set up"
        default: "4.13.0"
        type: string

jobs:
  lint:
    name: 🚨 Lint
    uses: ./.github/workflows/reusable-python-linter.yml
    with:
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}

  dist:
    name: 📦 Check
    runs-on: ubuntu-latest
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      # optionally set up Z3
      - if: ${{ inputs.setup-z3 }}
        name: Setup Z3
        uses: cda-tum/setup-z3@v1
        with:
          version: ${{ inputs.z3-version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      # set up mold as linker for faster C++ builds
      - name: Set up mold as linker
        uses: rui314/setup-mold@v1
      # run the build-and-inspect-python-package action (outputs supported Python versions)
      - uses: hynek/build-and-inspect-python-package@v2
        id: baipp
      # determine the maximum supported Python version
      - name: 🐍 Determine maximum supported Python version
        run: echo "max-python-version=$(echo '${{ steps.baipp.outputs.supported_python_classifiers_json_array }}' | jq --raw-output '.[-1]')" >> $GITHUB_OUTPUT
        id: max-python-version
    outputs:
      python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}
      max-python-version: ${{ steps.max-python-version.outputs.max-python-version }}

  python-tests-ubuntu:
    name: 🐧 ${{ matrix.python-version }}
    needs: dist
    strategy:
      fail-fast: false
      matrix:
        # runs Python testing for all supported Python versions on Ubuntu
        python-version: ${{ fromJson(needs.dist.outputs.python-versions) }}
    uses: ./.github/workflows/reusable-python-tests.yml
    with:
      runs-on: ubuntu-latest
      python-version: ${{ matrix.python-version }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}
    secrets:
      token: ${{ secrets.token }}

  python-tests-macos:
    name: 🍎 ${{ matrix.python-version }} ${{ matrix.runs-on }}
    needs: [dist]
    strategy:
      fail-fast: false
      matrix:
        # runs Python testing for the minimum and maximum supported Python versions on macOS
        python-version:
          - ${{ fromJson(needs.dist.outputs.python-versions)[0] }}
          - ${{ needs.dist.outputs.max-python-version }}
        runs-on: [macos-13, macos-14]
    uses: ./.github/workflows/reusable-python-tests.yml
    with:
      runs-on: ${{ matrix.runs-on }}
      python-version: ${{ matrix.python-version }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}
    secrets:
      token: ${{ secrets.token }}

  python-tests-windows:
    name: 🏁 ${{ matrix.python-version }}
    needs: [dist]
    strategy:
      fail-fast: false
      matrix:
        # runs Python testing for the minimum and maximum supported Python versions on Windows
        python-version:
          - ${{ fromJson(needs.dist.outputs.python-versions)[0] }}
          - ${{ needs.dist.outputs.max-python-version }}
    uses: ./.github/workflows/reusable-python-tests.yml
    with:
      runs-on: windows-latest
      python-version: ${{ matrix.python-version }}
      setup-z3: ${{ inputs.setup-z3 }}
      z3-version: ${{ inputs.z3-version }}
    secrets:
      token: ${{ secrets.token }}
